# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger: none
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'

#Task to package dependencies for Debricked Scan on FOD - using Debricked CLI Resolve option.
- task: CmdLine@2
  env:
     #Token not needed for this local Resolve command run.
     #DEBRICKED_TOKEN: $(DEBRICKED_TOKEN)
  inputs:
    script: |
      curl -L https://github.com/debricked/cli/releases/latest/download/cli_linux_x86_64.tar.gz | tar -xz debricked
      ./debricked resolve
  displayName: DeBricked CLI Resolve

# Task to run FOD SAST scan.
- task: FortifyOnDemandStatic@8
  inputs:
    FortifyProjects: 
    FodConnection: 'FOD-IWA-Java-Hans-app'
    ReleaseOptions: '0'
    ReleaseId: 1051009
    EntitlementSelection: '1'
    EntitlementPreference: '1'
    OverrideScanSettings: '2'
    InProgressScanActionType: '2'
    RemediationScanPreference: '2'
    BuildType: 'mvn'
    BuildCommand: 
    PolicyFailAction: '0'